#Screen Settings
SCREEN_WIDTH = 480
SCREEN_HEIGHT = 480
SCREEN_RES = (SCREEN_WIDTH, SCREEN_HEIGHT)

#Player Settings
PLAYER_WIDTH = 20
PLAYER_SIZE = (PLAYER_WIDTH, PLAYER_WIDTH)
PLAYER_SPEED = 1
PLAYER_TURNING_SPEED = 360/60

#Bullet Settings
BULLET_SIZE = (5, 5)
BULLET_SPEED = 4
BULLET_LIFESPAN = 200

#Debug
DEBUG = True